--     alter table mark 
--         drop constraint FK3306CD618FF289;
-- 
--     alter table mark 
--         drop constraint FK3306CDABAE0D6B;
-- 
--     alter table quote 
--         drop constraint FK66F3E7CAA231906;
-- 
--     alter table quote_tag 
--         drop constraint FKA7A08F57ABAE0D6B;
-- 
--     alter table quote_tag 
--         drop constraint FKA7A08F571E07248D;
-- 
--     alter table quotetag 
--         drop constraint FKCB9A1F9EBC8BF688;
-- 
--     alter table role_permission 
--         drop constraint FKBD40D53853413808;
-- 
--     alter table role_permission 
--         drop constraint FKBD40D538BC652EA9;
-- 
--     alter table systemuser 
--         drop constraint FK2660AE7ABC652EA9;
-- 
--     alter table user_quote 
--         drop constraint FK73374908618FF289;
-- 
--     alter table user_quote 
--         drop constraint FK73374908ABAE0D6B;

    drop table mark if exists;

    drop table quote if exists;

    drop table quote_tag if exists;

    drop table quotetag if exists;

    drop table role_permission if exists;

    drop table systemuser if exists;

    drop table user_quote if exists;

    drop table userpermission if exists;

    drop table userrole if exists;

    create table mark (
        id integer generated by default as identity,
        creationDate date,
        points integer,
        quote_id integer,
        user_id integer,
        primary key (id)
    );

    create table quote (
        id integer generated by default as identity,
        picture blob,
        uploadingDate date,
        uploader_id integer,
        primary key (id)
    );

    create table quote_tag (
        tag_id integer not null,
        quote_id integer not null
    );

    create table quotetag (
        id integer generated by default as identity,
        creationDate date,
        title varchar(255),
        creator_id integer,
        primary key (id)
    );

    create table role_permission (
        role_id integer not null,
        perm_id integer not null,
        primary key (role_id, perm_id)
    );

    create table systemuser (
        id integer generated by default as identity,
        login varchar(255),
        password varchar(255),
        regDate date,
        role_id integer,
        primary key (id)
    );

    create table user_quote (
        user_id integer not null,
        quote_id integer not null,
        primary key (user_id, quote_id)
    );

    create table userpermission (
        id integer generated by default as identity,
        permTitle varchar(255),
        primary key (id)
    );

    create table userrole (
        id integer generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    alter table mark 
        add constraint FK3306CD618FF289 
        foreign key (user_id) 
        references systemuser;

    alter table mark 
        add constraint FK3306CDABAE0D6B 
        foreign key (quote_id) 
        references quote;

    alter table quote 
        add constraint FK66F3E7CAA231906 
        foreign key (uploader_id) 
        references systemuser;

    alter table quote_tag 
        add constraint FKA7A08F57ABAE0D6B 
        foreign key (quote_id) 
        references quote;

    alter table quote_tag 
        add constraint FKA7A08F571E07248D 
        foreign key (tag_id) 
        references quotetag;

    alter table quotetag 
        add constraint FKCB9A1F9EBC8BF688 
        foreign key (creator_id) 
        references systemuser;

    alter table role_permission 
        add constraint FKBD40D53853413808 
        foreign key (perm_id) 
        references userpermission;

    alter table role_permission 
        add constraint FKBD40D538BC652EA9 
        foreign key (role_id) 
        references userrole;

    alter table systemuser 
        add constraint FK2660AE7ABC652EA9 
        foreign key (role_id) 
        references userrole;

    alter table user_quote 
        add constraint FK73374908618FF289 
        foreign key (user_id) 
        references systemuser;

    alter table user_quote 
        add constraint FK73374908ABAE0D6B 
        foreign key (quote_id) 
        references quote;
